setInterval(()=>{
const date=new Date();
/*let hour=document.getElementById("hr");
let minutes=document.getElementById("min");
let seconds=document.getElementById("sec");*/
 let hr=date.getHours();
 let min=date.getMinutes();
 let sec=date.getSeconds();
 let hrrotate=30*hr;
 let minrotate=6*min;
 let secrotate=6*sec;
hour.style.transform=`rotate(${hrrotate}deg)`
minutes.style.transform=`rotate(${minrotate}deg)`
seconds.style.transform=`rotate(${secrotate}deg)`},1000);
